"""The lineup file: rendered wholesale from configs, written atomically.

The file is llmbroker's own — see ``specs/reference/rules/sync-merge.md``.
"""

from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

import tomli_w

from llmbroker.broker.keys import KeyProbe
from llmbroker.broker.merge import SyncSource, merge_lineup
from llmbroker.models import KeyInfo, Lineup, LLMConfig, SyncReport
from llmbroker.protocols.store import StoreProtocol
from llmbroker.standalone.registry import read_lineup
from llmbroker.util.atomic import write_atomic

_HEADER = (
    "# Generated by llmbroker — rewritten in full on every sync.\n"
    "# A model you reach by name is declared in code with direct=[...], not written here."
)


def entry_block(section: str, entry: dict) -> str:
    """One ``[[section]]`` block. The header is written here rather than left to
    ``tomli_w``, which renders a short array of tables as an inline top-level key —
    written after a trailing ``[keys.*]`` table that parses as a member of that table."""
    return f"[[{section}]]\n{tomli_w.dumps(entry).rstrip()}"


def _entry_dict(cfg: LLMConfig) -> dict:
    entry: dict = {}
    entry["name"] = cfg.name
    entry["model"] = cfg.model
    entry["base_url"] = cfg.base_url
    entry["api_key_ref"] = cfg.api_key_ref
    if cfg.parallel is not None:
        entry["parallel"] = cfg.parallel
    if cfg.weight:
        entry["weight"] = cfg.weight
    return entry


def key_block(info: KeyInfo) -> dict:
    """One ``[keys.REF]`` table: the help plus whatever else the section carried,
    which is a documented passthrough and has to survive the round trip."""
    table: dict = {**info.extra}
    if info.help:
        table["help"] = info.help
    return table


def _keys_table(configs: Iterable[LLMConfig], keys: dict[str, KeyInfo]) -> dict:
    """The ``[keys]`` the rendered entries need. A ref nothing references any more
    carries no help worth keeping — the entry that wanted it is gone."""
    table: dict = {}
    for cfg in configs:
        ref = cfg.api_key_ref
        if not ref or ref in table or ref not in keys:
            continue
        block = key_block(keys[ref])
        if block:
            table[ref] = block
    return table


def render_lineup(lineup: Lineup) -> str:
    """The whole file: the pool entries, then ``[keys]``.

    Nothing is carried over from the previous text, so there is nothing to verify
    the result against.
    """
    parts = [_HEADER]
    parts.extend(entry_block("llms", _entry_dict(c)) for c in lineup.configs)
    table = _keys_table(lineup.configs, lineup.keys)
    if table:
        parts.append(tomli_w.dumps({"keys": table}).rstrip("\n"))
    return "\n\n".join(parts) + "\n"


def write_lineup(path: Path, lineup: Lineup) -> bool:
    """Render and write, and say whether the file changed.

    Compared on the exact bytes that would be written, so an upstream change
    carrying only a key hint still counts: the file's git history is the record.
    """
    rendered = render_lineup(lineup)
    if path.exists() and path.read_text(encoding="utf-8") == rendered:
        return False
    write_atomic(path, rendered)
    return True


@dataclass(frozen=True, slots=True)
class FileSyncOutcome:
    """The result of syncing the file: the report, whether it was rewritten, and the
    merged lineup."""

    report: SyncReport
    changed: bool
    configs: tuple[LLMConfig, ...] = ()


async def sync_lineup_file(
    path: Path,
    src: SyncSource,
    *,
    probe: KeyProbe,
    store: StoreProtocol | None = None,
) -> FileSyncOutcome:
    """Merge ``src`` into the lineup file at ``path`` and rewrite it.

    Any error leaves the file untouched.
    """
    if path.suffix.lower() != ".toml":
        raise ValueError(f"sync target must be a .toml file, got {path}")
    outcome = await merge_lineup(src, read_lineup(path), probe=probe, store=store)
    return FileSyncOutcome(
        report=outcome.report,
        changed=write_lineup(path, outcome.lineup),
        configs=tuple(outcome.lineup.configs),
    )
