"""The lineup file: rendered wholesale, written atomically, and the file target
end to end."""

import stat
import tomllib

import pytest

from llmbroker.broker.keys import KeyProbe
from llmbroker.broker.lineup_file import FileSyncOutcome, render_lineup, sync_lineup_file
from llmbroker.broker.merge import SyncSource
from llmbroker.models import KeyInfo, Lineup, LLMConfig
from llmbroker.standalone.registry import parse_lineup
from llmbroker.standalone.secrets import DictSecrets, Secrets
from llmbroker.util.atomic import write_atomic


def _cfg(name, ref="K", *, model="m", url="https://x/v1"):
    return LLMConfig(name=name, base_url=url, model=model, api_key_ref=ref)


# ── Rendering ────────────────────────────────────────────────────────────────


def test_the_render_reads_back_as_the_lineup_it_was_given():
    lineup = Lineup(
        configs=[_cfg("pool"), _cfg("second", "K", model="m2")],
        keys={"K": KeyInfo(api_key_ref="K", help="k help", extra={})},
    )
    read_back = parse_lineup(tomllib.loads(render_lineup(lineup)))
    assert [(c.name, c.model, c.alias) for c in read_back.configs] == [
        ("pool", "m", None),
        ("second", "m2", None),
    ]
    assert read_back.keys["K"].help == "k help"


def test_the_render_has_one_array():
    """A model reached by name is declared in code, so the file states the pool only."""
    text = render_lineup(Lineup(configs=[_cfg("pool"), _cfg("second", model="m2")]))
    data = tomllib.loads(text)
    assert set(data) == {"llms"}


def test_a_short_entry_stays_top_level_after_a_keys_table():
    """tomli_w renders a short array of tables inline, which after a [keys.*] table
    parses as a member of it — every entry must carry its own explicit header."""
    lineup = Lineup(
        configs=[_cfg("l", "K", url="http://h/v1"), _cfg("c", "K", url="http://h/v1")],
        keys={"K": KeyInfo(api_key_ref="K", help="k", extra={})},
    )
    data = tomllib.loads(render_lineup(lineup))
    assert [e["name"] for e in data["llms"]] == ["l", "c"]
    assert set(data["keys"]["K"]) == {"help"}


def test_the_key_info_passthrough_survives_the_round_trip():
    """``extra`` is documented as a passthrough llmbroker has no opinion on, so a
    rewrite may not quietly drop what a preset author put there."""
    lineup = Lineup(
        configs=[_cfg("pool", "K")],
        keys={"K": KeyInfo(api_key_ref="K", help="get it here", extra={"effort": "low"})},
    )
    read_back = parse_lineup(tomllib.loads(render_lineup(lineup)))
    assert read_back.keys["K"] == KeyInfo(
        api_key_ref="K",
        help="get it here",
        extra={"effort": "low"},
    )


def test_a_key_no_entry_references_is_not_rendered():
    lineup = Lineup(
        configs=[_cfg("pool", "K")],
        keys={"K": KeyInfo("K", "k help", {}), "GONE": KeyInfo("GONE", "orphan help", {})},
    )
    assert set(tomllib.loads(render_lineup(lineup))["keys"]) == {"K"}


def test_the_file_says_it_is_generated_and_where_a_named_model_goes():
    text = render_lineup(Lineup(configs=[_cfg("pool")]))
    assert text.startswith("# Generated by llmbroker")
    assert "direct=[...]" in text


# ── The atomic write ─────────────────────────────────────────────────────────


def test_write_atomic_leaves_no_temp_files(tmp_path):
    target = tmp_path / "llms.toml"
    write_atomic(target, "a = 1\n")
    assert target.read_text() == "a = 1\n"
    assert [p.name for p in tmp_path.iterdir()] == ["llms.toml"]


def test_write_atomic_keeps_the_targets_permissions(tmp_path):
    """The temp file is created 0600 and os.replace carries its mode over — a runtime
    sync must not lock the serving process out of the config it just rewrote."""
    target = tmp_path / "llms.toml"
    target.write_text("a = 1\n")
    target.chmod(0o644)
    # Windows honors only the read-only bit, so 0o644 lands there as 0o666. Assert the
    # mode the OS actually granted survives the write, not the one that was requested.
    granted = stat.S_IMODE(target.stat().st_mode)
    write_atomic(target, "a = 2\n")
    assert stat.S_IMODE(target.stat().st_mode) == granted


def test_write_atomic_creates_a_missing_target_without_reading_a_mode(tmp_path):
    target = tmp_path / "fresh.toml"
    write_atomic(target, "a = 1\n")
    assert target.read_text() == "a = 1\n"


# ── The file target, end to end ──────────────────────────────────────────────

_NEW = (
    '[[llms]]\nname = "gemini"\nbase_url = "https://g/v1"\nmodel = "m"\n'
    'api_key_ref = "GEMINI_API_KEY"\n\n[keys.GEMINI_API_KEY]\nhelp = "gemini help"\n'
)


def _source(text: str, label: str = "freetier") -> SyncSource:
    return SyncSource(label=label, lineup=parse_lineup(tomllib.loads(text)))


async def _sync(target, text=_NEW, *, secrets=None, source="freetier", **kwargs) -> FileSyncOutcome:
    return await sync_lineup_file(
        target,
        _source(text, source),
        probe=KeyProbe(secrets if secrets is not None else DictSecrets({})),
        **kwargs,
    )


def _write_current(tmp_path, body, name="llms.toml"):
    target = tmp_path / name
    target.write_text(body)
    return target


async def test_it_keeps_a_dropped_entry_without_a_usable_replacement(tmp_path):
    target = _write_current(
        tmp_path,
        '[[llms]]\nname="groq-old"\nbase_url="https://groq/v1"\nmodel="m"'
        '\napi_key_ref="GROQ_API_KEY"\n[keys.GROQ_API_KEY]\nhelp = "groq help"\n',
    )
    outcome = await _sync(target)
    data = tomllib.loads(target.read_text())
    assert [e["name"] for e in data["llms"]] == ["gemini", "groq-old"]
    assert data["keys"]["GROQ_API_KEY"]["help"] == "groq help"
    assert outcome.report.kept == ("groq-old",)


async def test_a_curated_weight_survives_the_rewrite(tmp_path):
    """A kept entry is re-emitted from its config, so a weight the curator wrote is
    stripped unless the writer emits it too."""
    target = _write_current(
        tmp_path,
        '[[llms]]\nname="groq-old"\nbase_url="https://groq/v1"\nmodel="m"'
        '\napi_key_ref="GROQ_API_KEY"\nweight=0.55\n'
        '[[llms]]\nname="mine"\nbase_url="https://mine/v1"\nmodel="m"'
        '\napi_key_ref="MY_KEY"\nweight=0.4\n',
    )
    await _sync(target)
    data = tomllib.loads(target.read_text())
    weights = {e["name"]: e.get("weight") for e in data["llms"]}
    assert weights == {"gemini": None, "groq-old": 0.55, "mine": 0.4}


async def test_it_removes_the_dropped_entry_once_the_arrivals_key_is_there(tmp_path):
    target = _write_current(
        tmp_path,
        '[[llms]]\nname="groq-old"\nbase_url="https://groq/v1"\nmodel="m"'
        '\napi_key_ref="GROQ_API_KEY"\n',
    )
    outcome = await _sync(target, secrets=DictSecrets({"GEMINI_API_KEY": "sk-x"}))
    assert [e["name"] for e in tomllib.loads(target.read_text())["llms"]] == ["gemini"]
    assert outcome.report.removed == ("groq-old",)


async def test_the_sibling_env_file_counts_as_a_key(tmp_path):
    """The CLI resolves exactly what the application will — env plus the file's own .env."""
    target = _write_current(
        tmp_path,
        '[[llms]]\nname="groq-old"\nbase_url="https://groq/v1"\nmodel="m"'
        '\napi_key_ref="GROQ_API_KEY"\n',
    )
    (tmp_path / ".env").write_text("GEMINI_API_KEY=sk-from-file\n")
    outcome = await _sync(target, secrets=Secrets(tmp_path / ".env"))
    assert outcome.report.removed == ("groq-old",)


async def test_a_refusal_leaves_the_file_untouched(tmp_path):
    target = _write_current(
        tmp_path,
        '[[llms]]\nname="gemini"\nbase_url="https://g/v1"\nmodel="old"\napi_key_ref="GEMINI_API_KEY"\n',
    )
    original = target.read_text()
    with pytest.raises(ValueError, match="refusing to change model"):
        await _sync(target)
    assert target.read_text() == original


async def test_the_key_help_for_a_kept_entry_survives_a_sync(tmp_path):
    """The one key still missing is usually the user's own, so a sync that dropped
    its help would erase the instructions for the one irreducible admin act."""
    target = _write_current(
        tmp_path,
        '[[llms]]\nname="mine"\nbase_url="https://mine/v1"\nmodel="m"'
        '\napi_key_ref="MY_KEY"\n[keys.MY_KEY]\nhelp = "my help"\n',
    )
    await _sync(target)
    assert tomllib.loads(target.read_text())["keys"]["MY_KEY"]["help"] == "my help"


async def test_an_empty_lineup_loses_nothing(tmp_path):
    target = _write_current(
        tmp_path,
        '[[llms]]\nname="groq-old"\nbase_url="https://groq/v1"\nmodel="m"\napi_key_ref="G"\n',
    )
    outcome = await _sync(target, "", secrets=DictSecrets({"G": "sk"}))
    assert [e["name"] for e in tomllib.loads(target.read_text())["llms"]] == ["groq-old"]
    assert outcome.report.kept == ("groq-old",)


async def test_a_missing_target_is_created(tmp_path):
    target = tmp_path / "new.toml"
    outcome = await _sync(target)
    assert [e["name"] for e in tomllib.loads(target.read_text())["llms"]] == ["gemini"]
    assert outcome.report.added == ("gemini",)


async def test_a_non_toml_target_is_refused(tmp_path):
    with pytest.raises(ValueError, match=".toml"):
        await _sync(tmp_path / "llms.json")


# ── A kept entry ─────────────────────────────────────────────────────────────


async def test_a_kept_entry_is_carried_over_with_the_hint_for_its_key(tmp_path):
    """The key help is the only thing llmbroker offers for the one irreducible admin
    act, so a sync that dropped it would erase the instructions for a key still
    missing. Repeated, because the first pass carries it through the merge and only
    the second reads it back from what was written."""
    target = _write_current(
        tmp_path,
        '[[llms]]\nname="mine"\nbase_url="https://mine/v1"\nmodel="big"\napi_key_ref="MY_KEY"\n'
        '[keys.MY_KEY]\nhelp = "where to get my key"\n',
    )
    for _ in range(2):
        outcome = await _sync(target)
    keys = tomllib.loads(target.read_text())["keys"]
    assert keys["MY_KEY"]["help"] == "where to get my key"
    assert [p.help for p in outcome.report.pending_keys if p.api_key_ref == "MY_KEY"] == [
        "where to get my key",
    ]


async def test_a_hint_no_entry_needs_any_more_is_dropped(tmp_path):
    """The entry that wanted it is gone; keeping its help would be advice about a key
    nothing here can use."""
    target = _write_current(
        tmp_path,
        '[keys.STALE]\nhelp = "for an entry that no longer exists"\n',
    )
    await _sync(target)
    assert set(tomllib.loads(target.read_text())["keys"]) == {"GEMINI_API_KEY"}


# ── The identity gate ────────────────────────────────────────────────────────


async def test_an_unchanged_sync_leaves_the_target_byte_identical(tmp_path):
    target = _write_current(tmp_path, "")
    assert (await _sync(target)).changed is True

    text, mtime = target.read_text(), target.stat().st_mtime_ns
    second = await _sync(target)
    assert second.changed is False
    assert target.read_text() == text
    assert target.stat().st_mtime_ns == mtime


async def test_a_moved_key_hint_still_rewrites_the_file(tmp_path):
    target = _write_current(tmp_path, "")
    await _sync(target)
    moved = _NEW.replace('help = "gemini help"', 'help = "new help"')
    assert (await _sync(target, moved)).changed is True
    assert "new help" in target.read_text()


async def test_a_preset_whose_only_change_is_a_weight_rewrites_the_file(tmp_path):
    target = _write_current(tmp_path, "")
    await _sync(target)
    reweighted = _NEW.replace(
        'api_key_ref = "GEMINI_API_KEY"\n\n',
        'api_key_ref = "GEMINI_API_KEY"\nweight = 0.75\n\n',
    )
    assert (await _sync(target, reweighted)).changed is True
    assert "weight = 0.75" in target.read_text()


async def test_a_kept_entry_does_not_duplicate_over_repeated_syncs(tmp_path):
    target = _write_current(
        tmp_path,
        '[[llms]]\nname="groq-old"\nbase_url="https://groq/v1"\nmodel="m"\napi_key_ref="G"\n',
    )
    for _ in range(3):
        outcome = await _sync(target)
    assert [e["name"] for e in tomllib.loads(target.read_text())["llms"]] == [
        "gemini",
        "groq-old",
    ]
    assert (outcome.report.kept, outcome.report.added) == (("groq-old",), ())
