"""The model list file: rendered wholesale, written atomically, and the file target
end to end."""

import stat
import tomllib

import pytest

from llmbroker.broker.model_list_file import (
    FileSyncOutcome,
    render_model_list,
    sync_model_list_file,
)
from llmbroker.broker.merge import SyncSource
from llmbroker.exceptions import SyncRefusedError
from llmbroker.models import KeyInfo, ModelList, LLMConfig
from llmbroker.standalone.registry import parse_model_list
from llmbroker.util.atomic import write_atomic


def _cfg(name, ref="K", *, model="m", url="https://x/v1"):
    return LLMConfig(name=name, base_url=url, model=model, api_key_ref=ref)


# ── Rendering ────────────────────────────────────────────────────────────────


def test_the_render_reads_back_as_the_model_list_it_was_given():
    model_list = ModelList(
        configs=[_cfg("pool"), _cfg("second", "K", model="m2")],
        keys={"K": KeyInfo(api_key_ref="K", help="k help", extra={})},
    )
    read_back = parse_model_list(tomllib.loads(render_model_list(model_list)))
    assert [(c.name, c.model, c.alias) for c in read_back.configs] == [
        ("pool", "m", None),
        ("second", "m2", None),
    ]
    assert read_back.keys["K"].help == "k help"


def test_the_render_has_one_array():
    """A model reached by name is declared in code, so the file states the pool only."""
    text = render_model_list(ModelList(configs=[_cfg("pool"), _cfg("second", model="m2")]))
    data = tomllib.loads(text)
    assert set(data) == {"llms"}


def test_a_short_entry_stays_top_level_after_a_keys_table():
    """tomli_w renders a short array of tables inline, which after a [keys.*] table
    parses as a member of it — every entry must carry its own explicit header."""
    model_list = ModelList(
        configs=[_cfg("l", "K", url="http://h/v1"), _cfg("c", "K", url="http://h/v1")],
        keys={"K": KeyInfo(api_key_ref="K", help="k", extra={})},
    )
    data = tomllib.loads(render_model_list(model_list))
    assert [e["name"] for e in data["llms"]] == ["l", "c"]
    assert set(data["keys"]["K"]) == {"help"}


def test_the_key_info_passthrough_survives_the_round_trip():
    """``extra`` is documented as a passthrough llmbroker has no opinion on, so a
    rewrite may not quietly drop what a preset author put there."""
    model_list = ModelList(
        configs=[_cfg("pool", "K")],
        keys={"K": KeyInfo(api_key_ref="K", help="get it here", extra={"effort": "low"})},
    )
    read_back = parse_model_list(tomllib.loads(render_model_list(model_list)))
    assert read_back.keys["K"] == KeyInfo(
        api_key_ref="K",
        help="get it here",
        extra={"effort": "low"},
    )


def test_a_key_no_entry_references_is_not_rendered():
    model_list = ModelList(
        configs=[_cfg("pool", "K")],
        keys={"K": KeyInfo("K", "k help", {}), "GONE": KeyInfo("GONE", "orphan help", {})},
    )
    assert set(tomllib.loads(render_model_list(model_list))["keys"]) == {"K"}


def test_the_file_says_it_is_generated_and_where_a_named_model_goes():
    text = render_model_list(ModelList(configs=[_cfg("pool")]))
    assert text.startswith("# Generated by llmbroker")
    assert "direct=[...]" in text


# ── The atomic write ─────────────────────────────────────────────────────────


def test_write_atomic_leaves_no_temp_files(tmp_path):
    target = tmp_path / "llms.toml"
    write_atomic(target, "a = 1\n")
    assert target.read_text() == "a = 1\n"
    assert [p.name for p in tmp_path.iterdir()] == ["llms.toml"]


def test_write_atomic_keeps_the_targets_permissions(tmp_path):
    """The temp file is created 0600 and os.replace carries its mode over — a runtime
    sync must not lock the serving process out of the config it just rewrote."""
    target = tmp_path / "llms.toml"
    target.write_text("a = 1\n")
    target.chmod(0o644)
    # Windows honors only the read-only bit, so 0o644 lands there as 0o666. Assert the
    # mode the OS actually granted survives the write, not the one that was requested.
    granted = stat.S_IMODE(target.stat().st_mode)
    write_atomic(target, "a = 2\n")
    assert stat.S_IMODE(target.stat().st_mode) == granted


def test_write_atomic_creates_a_missing_target_without_reading_a_mode(tmp_path):
    target = tmp_path / "fresh.toml"
    write_atomic(target, "a = 1\n")
    assert target.read_text() == "a = 1\n"


# ── The file target, end to end ──────────────────────────────────────────────

_NEW = (
    '[[llms]]\nname = "gemini"\nbase_url = "https://g/v1"\nmodel = "m"\n'
    'api_key_ref = "GEMINI_API_KEY"\n\n[keys.GEMINI_API_KEY]\nhelp = "gemini help"\n'
)


def _source(text: str, label: str = "freetier") -> SyncSource:
    return SyncSource(label=label, model_list=parse_model_list(tomllib.loads(text)))


def _sync(target, text=_NEW, *, present=frozenset(), source="freetier") -> FileSyncOutcome:
    return sync_model_list_file(target, _source(text, source), present=present)


def _write_current(tmp_path, body, name="llms.toml"):
    target = tmp_path / name
    target.write_text(body)
    return target


async def test_it_removes_a_dropped_entry_though_its_key_is_here(tmp_path):
    """The file is llmbroker's own output, so everything in it is a sync's and the
    result is the arriving list — no key weighs on that."""
    target = _write_current(
        tmp_path,
        '[[llms]]\nname="groq-old"\nbase_url="https://groq/v1"\nmodel="m"'
        '\napi_key_ref="GROQ_API_KEY"\n[keys.GROQ_API_KEY]\nhelp = "groq help"\n',
    )
    outcome = _sync(target, present=frozenset({"GROQ_API_KEY"}))
    data = tomllib.loads(target.read_text())
    assert [e["name"] for e in data["llms"]] == ["gemini"]
    assert "GROQ_API_KEY" not in data["keys"]
    assert (outcome.report.removed, outcome.report.orphan_refs) == (
        ("groq-old",),
        ("GROQ_API_KEY",),
    )


async def test_a_curated_weight_survives_the_rewrite(tmp_path):
    """An entry is re-emitted from its config, so a weight the curator wrote is
    stripped unless the writer emits it too."""
    target = _write_current(tmp_path, "")
    _sync(
        target,
        '[[llms]]\nname="gemini"\nbase_url="https://g/v1"\nmodel="m"'
        '\napi_key_ref="GEMINI_API_KEY"\nweight=0.55\n',
    )
    data = tomllib.loads(target.read_text())
    assert {e["name"]: e.get("weight") for e in data["llms"]} == {"gemini": 0.55}


async def test_a_refusal_leaves_the_file_untouched(tmp_path):
    target = _write_current(
        tmp_path,
        '[[llms]]\nname="gemini"\nbase_url="https://g/v1"\nmodel="old"\napi_key_ref="GEMINI_API_KEY"\n',
    )
    original = target.read_text()
    with pytest.raises(ValueError, match="refusing to change model"):
        _sync(target)
    assert target.read_text() == original


async def test_an_empty_arriving_list_over_a_filled_file_is_refused(tmp_path):
    """The structural guard is what stops a fetch that returned nothing from emptying
    a working installation — the mirror alone would."""
    target = _write_current(
        tmp_path,
        '[[llms]]\nname="groq-old"\nbase_url="https://groq/v1"\nmodel="m"\napi_key_ref="G"\n',
    )
    original = target.read_text()
    with pytest.raises(SyncRefusedError):
        _sync(target, "", present=frozenset({"G"}))
    assert target.read_text() == original


async def test_a_missing_target_is_created(tmp_path):
    target = tmp_path / "new.toml"
    outcome = _sync(target)
    assert [e["name"] for e in tomllib.loads(target.read_text())["llms"]] == ["gemini"]
    assert outcome.report.added == ("gemini",)


async def test_a_non_toml_target_is_refused(tmp_path):
    with pytest.raises(ValueError, match=".toml"):
        _sync(tmp_path / "llms.json")


# ── The key help ─────────────────────────────────────────────────────────────


async def test_the_hint_for_a_missing_key_survives_a_repeated_sync(tmp_path):
    """The key help is the only thing llmbroker offers for the one irreducible admin
    act, so a sync that dropped it would erase the instructions for a key still
    missing. Repeated, because the first pass carries it through the merge and only
    the second reads it back from what was written."""
    target = _write_current(tmp_path, "")
    for _ in range(2):
        outcome = _sync(target)
    keys = tomllib.loads(target.read_text())["keys"]
    assert keys["GEMINI_API_KEY"]["help"] == "gemini help"
    assert [p.help for p in outcome.report.pending_keys] == ["gemini help"]


async def test_a_hint_no_entry_needs_any_more_is_dropped(tmp_path):
    """The entry that wanted it is gone; keeping its help would be advice about a key
    nothing here can use."""
    target = _write_current(
        tmp_path,
        '[keys.STALE]\nhelp = "for an entry that no longer exists"\n',
    )
    _sync(target)
    assert set(tomllib.loads(target.read_text())["keys"]) == {"GEMINI_API_KEY"}


# ── The identity gate ────────────────────────────────────────────────────────


async def test_an_unchanged_sync_leaves_the_target_byte_identical(tmp_path):
    target = _write_current(tmp_path, "")
    assert _sync(target).changed is True

    text, mtime = target.read_text(), target.stat().st_mtime_ns
    second = _sync(target)
    assert second.changed is False
    assert target.read_text() == text
    assert target.stat().st_mtime_ns == mtime
